name: ERaces
version: ${version}
main: dev.elysium.eraces.ERaces
description: Просто плагин на расы
api-version: '1.21.8'

commands:
  races:
    description: "Коаманда на расы типо"
    permission: eraces.races_command.use
  myrace:
    description: "Показывает расу игрока"
    usage: /myrace
  abils:
    usage: /abils <id>


permissions:
  fdp_races.races_command.use:
    default: op

libraries:
  - org.xerial:sqlite-jdbc:3.50.3.0