name: ERaces
version: ${version}
main: dev.elysium.eraces.ERaces
description: Просто плагин на расы
website: 'https://github.com/FreedomDevs/ERaces'
api-version: '1.21.4'
authors:
  # Lead Developers
  - Foksif
  - mikinol
  # Current Developers
  - L1nkolb154
  - TheRealFrogman
  # Former Developers
  - TF-64
  # Other Contributors (not official team, just occasional PRs)
  - dimcaftv
softdepend: [PlaceholderAPI]

commands:
  races:
    description: "Коаманда на расы типо"
    permission: eraces.races_command.use
  myrace:
    description: "Показывает расу игрока"
    usage: /myrace
  abils:
    usage: /abils <id>


permissions:
  fdp_races.races_command.use:
    default: op

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.2.21
  - org.jetbrains.kotlin:kotlin-reflect:2.2.21
  - org.xerial:sqlite-jdbc:3.51.0.0
  - org.luaj:luaj-jse:3.0.1