package dev.elysium.eraces.exceptions

enum class ErrorCodes(val code: String) {
    INTERNAL_ERROR("INTERNAL_ERROR"),
    PLAYER_ERROR("PLAYER_ERROR"),

    ABILITY_ACTIVATION("ABILITY_ACTIVATION_ERROR"),
    ABILITY_REGISTRATION("ABILITY_REGISTRATION_ERROR"),
    CONFIG_LOAD("CONFIG_LOAD_ERROR"),
    CONFIG_SAVE("CONFIG_SAVE_ERROR"),
    CONFIG_PARAM("CONFIG_PARAM"),
    ABILITY_DUPLICATE("ABILITY_DUPLICATE"),
    INIT_FAILED("INIT_FAILED"),
    XP_INTERNAL_ERROR("XP_INTERNAL_ERROR"),

    PLAYER_RACE_NOT_SELECTED("PLAYER_RACE_NOT_SELECTED"),
    PLAYER_ABILITY_NOT_FOUND("PLAYER_ABILITY_NOT_FOUND"),
    PLAYER_ABILITY_NOT_OWNED("PLAYER_ABILITY_NOT_OWNED"),
    PLAYER_ABILITY_COOLDOWN("PLAYER_ABILITY_COOLDOWN");
}
