package dev.elysium.eraces.exceptions

object ErrorCodes {
    const val INTERNAL_ERROR = "INTERNAL_ERROR"
    const val PLAYER_ERROR = "PLAYER_ERROR"

    const val ABILITY_ACTIVATION = "ABILITY_ACTIVATION_ERROR"
    const val ABILITY_REGISTRATION = "ABILITY_REGISTRATION_ERROR"
    const val CONFIG_LOAD = "CONFIG_LOAD_ERROR"
    const val CONFIG_SAVE = "CONFIG_SAVE_ERROR"
    const val ABILITY_DUPLICATE = "ABILITY_DUPLICATE"
    const val INIT_FAILED = "INIT_FAILED"
    const val XP_INTERNAL_ERROR = "XP_INTERNAL_ERROR"

    const val PLAYER_RACE_NOT_SELECTED = "PLAYER_RACE_NOT_SELECTED"
    const val PLAYER_ABILITY_NOT_FOUND = "PLAYER_ABILITY_NOT_FOUND"
    const val PLAYER_ABILITY_NOT_OWNED = "PLAYER_ABILITY_NOT_OWNED"
    const val PLAYER_ABILITY_COOLDOWN = "PLAYER_ABILITY_COOLDOWN"
}
